# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-10 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20190303_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='wine',
            field=models.CharField(max_length=200),
        ),
    ]
